spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.209.205:3306/yanger?useSSL=false&amp;useUnicode=true&amp;characterEncoding=utf-8
    username: wocai
    password: 123456
  redis:
    host: localhost
    port: 6379
    timeout: 180000
  servlet:
    multipart:
      #设置上传文件根路径
      location: E:/

#日志文件位置
logging:
  file: D:/code/log/yanger.log

#添加服务器ip，供获取图片
yanger:
  file-load-prefix: 127.0.0.1

# 本地开发的时候可以关掉了swagger对于token的验证
swagger:
  token-check: true